name: Deploy to server
on:
  push:
    branches:
      - 'main'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ vars.FTP_HOST }}
          port: ${{ vars.FTP_PORT }}
          username: ${{ vars.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          protocol: ftps
          server-dir: ${{ vars.THEME_PATH }} 
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/scss/**
