name: Deploy to server
on:
  push:
    branches:
      - 'main'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install packages
        working-directory: ./themes/lsp
        run: npm install

      - name: Build assets
        working-directory: ./themes/lsp
        run: npm run build

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ vars.FTP_HOST }}
          port: ${{ vars.FTP_PORT }}
          username: ${{ vars.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          protocol: ftps
          server-dir: ${{ vars.THEME_PATH }} 
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/scss/**
