name: Deploy to server
on:
  push:
    branches:
      - 'main'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p $SERVER_PORT $SERVER_HOST >> ~/.ssh/known_hosts
          sudo apt-get install sshpass
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SERVER_PORT: ${{vars.SERVER_PORT}}
          SERVER_HOST: ${{vars.SERVER_HOST}}

      - name: Deploy to server
        run: |
          sshpass -p '$SSH_PASS' 
          ssh -v -o StrictHostKeyChecking=no -p $SERVER_PORT $SERVER_USER@$SERVER_HOST <<'ENDSSH'
          cd ${{ vars.THEME_PATH }}
          git pull
          ENDSSH
        env:
          SERVER_PORT: ${{vars.SERVER_PORT}}
          SERVER_HOST: ${{vars.SERVER_HOST}}
          SERVER_USER: ${{vars.SERVER_USER}}
          SSH_PASS: ${{ secrets.SSH_KEY_PASS }}
